// // TODO: Replace with file generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {

//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;

//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBei9mr7XbKM231S18pe55l812K1dC4kV8',
//     appId: '1:456114151431:web:9765b3a5c69e77c623caa2',
//     authDomain: "one-piece-b44fe.firebaseapp.com"
//     ,storageBucket:"one-piece-b44fe.appspot.com" ,
//     databaseURL: "https://one-piece-b44fe-default-rtdb.firebaseio.com",
//     messagingSenderId: '456114151431',
//     projectId: 'one-piece-b44fe',

//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBei9mr7XbKM231S18pe55l812K1dC4kV8',
//     appId: '1:456114151431:android:bd3a6ca9b73cb1fb23caa2',
//     storageBucket:"one-piece-b44fe.appspot.com" ,
//     messagingSenderId: '456114151431',
//     databaseURL: "https://one-piece-b44fe-default-rtdb.firebaseio.com",
//     projectId: 'one-piece-b44fe',
//     authDomain: "one-piece-b44fe.firebaseapp.com",
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBei9mr7XbKM231S18pe55l812K1dC4kV8',
//     appId: '1:456114151431:ios:cd06c8d3108daa2a23caa2',
//     databaseURL: "https://one-piece-b44fe-default-rtdb.firebaseio.com",
//     storageBucket:"one-piece-b44fe.appspot.com" ,
//     messagingSenderId: '456114151431',
//     projectId: 'one-piece-b44fe',
//     authDomain: "one-piece-b44fe.firebaseapp.com",
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBei9mr7XbKM231S18pe55l812K1dC4kV8',
//     appId: '1:456114151431:ios:cd06c8d3108daa2a23caa2',
//     databaseURL: "https://one-piece-b44fe-default-rtdb.firebaseio.com",
//     storageBucket:"one-piece-b44fe.appspot.com" ,
//     messagingSenderId: '456114151431',
//     projectId: 'one-piece-b44fe',
//     authDomain: "one-piece-b44fe.firebaseapp.com",
//   );
// }
